# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Builder stage
FROM node:lts-alpine AS builder
WORKDIR /app

# Install all dependencies including dev
COPY package.json package-lock.json ./
RUN npm install

# Copy source and build
COPY tsconfig.json ./
COPY src ./src
RUN npm run build

# Remove dev dependencies
RUN npm prune --production

# Runtime stage
FROM node:lts-alpine AS runtime
WORKDIR /app

# Copy built code and production dependencies
COPY --from=builder /app/build ./build
COPY --from=builder /app/node_modules ./node_modules
COPY package.json ./

# Default command
CMD ["node", "build/index.js"]
